# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912e66b416414f4f273009c7b2a6028e8857fa3ec7b065504c20440745a3aca1f865a37a31205571c624f63d707fb3f4787636829677710d8aee7b28223e0960

test:
  secret_key_base: cef1f8af17342cae5e530ae7f9068d6e58326ffac37ea38a1aa5ad0d35d7e47011676a48b3d5ba80db89314207a35b3b3cec86d9cf15ceec82534984950325cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
